
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/vitor/Documents/git/Clion/clion-2024.2.1/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-44-generic - x86_64
...
